### ISSUE TITLE
Async doesn't work with a_run_script (?)

### ISSUE THREAD

**Issue by karolzlot** [spyoungtech/ahk#141]
Sync version works for me (I can change value to 0 or to 1 and I see effect), but async version (code below) doesn't make any effect.

```python
from ahk import AsyncAHK
import asyncio
ahk = AsyncAHK()

async def main():

    ahk_script = r'RegWrite,REG_DWORD,HKCU,SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize,ColorPrevalence,1'
    await ahk.a_run_script(ahk_script, blocking=False)

    # await ahk.mouse_move(100, 100)
    # x, y = await ahk.get_mouse_position()
    # print(x, y)

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by spyoungtech** [comment]
If you use `blocking=True` (or omit the argument) does that fix the issue?

**Comment by karolzlot** [comment]
@spyoungtech 

Yes, with `blocking=True` it works ok.

Not sure why, but now it works even with `blocking=False`, however not reliably, sometimes works, sometimes not; and it gives error:
```
c:\EDITED\.venv_win\lib\site-packages\ahk\script.py:194: UserWarning: blocking=False will probably result in problems
  result = await self._a_run_script(script_text, decode=decode, blocking=blocking, **runkwargs)

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F67BC46E60>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F67BC46E60>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F67BC46E60>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 115, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001F67BC45480>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Python310\lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
  File "C:\Python310\lib\asyncio\proactor_events.py", line 79, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```

**Comment by spyoungtech** [comment]
Yeah, I think this is kind of expected. That's why the [warning is emitted](https://github.com/spyoungtech/ahk/blob/0bf9fb7f57ac5710c20d4909af12b42eb5f9276a/ahk/script.py#L158-L162):

> UserWarning: blocking=False will probably result in problems
